testlib.ProduceExitError: Use exec.CommandContext
This commit updates ProduceExitError to use exec.CommandContext. This
also requires passing a testing.T to the function.